kind: pipeline
name: default

steps:

  - name: aws-cdk
    image: eignhpants/docker-aws-cdk
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: sheeta_aws_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: sheeta_aws_secret
    commands:
    - npm install
    - cdk --output template synth
    - ls -la template
    - echo "done"
